// app/layout.js ya app/layout.tsx
import { Open_Sans, Playfair_Display } from "next/font/google";
import "./globals.css";

// Open Sans font setup
const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  // weight: ["400", "600", "700"],
});

// Playfair Display font setup
const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  // weight: ["400", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${playfair.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
